title: Workshop on Molecular Evolution
director: Tracy Heath
codirector: Jeremy Brown
logo_filename: tshirt-2019.png
email: moledirector@mbl.edu
description: >-
  Since 1988, the Workshop on Molecular Evolution at Woods Hole has 
  provided essential training in the theory and methods of molecular evolution.

baseurl: ""
#baseurl: "/people/plewis/wh2020"

header_pages:
   - about.md
   - people.md
   - schedule.md
   - other.md

url: ""
#twitter_username: jekyllrb
facebook_username: MolEvolWorkshop
#github_username:  molevolworkshop
show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Exclude from processing.
exclude:
   - faculty/huerta-sanchez
